#app_api:
#    resource: "@AppApiBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#app_core_domain:
#    resource: "@AppCoreDomainBundle/Controller/"
#    type:     annotation
#    prefix:   /
imports:
    resource: "@AppApiBundle/Resources/config/routing.yml"