#app_api:
#    resource: "@AppApiBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
app_core_domain:
    path:  /
    defaults: { _controller: AppCoreDomainBundle:Default:index, _format: ~ }
imports:
    resource: "@AppApiBundle/Resources/config/routing.yml"